package com.savis.springboot.dao.model;
// Generated Oct 2, 2017 5:48:40 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import com.fasterxml.jackson.annotation.JsonIgnore;


/**
 * Huyen generated by hbm2java
 */
@Entity
@Table(name = "huyen", catalog = "mycontact")
public class Huyen implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	//@NotNull(message = "idHuyen cannt be null")
    //@Size(min = 1, max = 30, message = "min 1, max 20")
	private Integer idHuyen;
	
	private Tinh tinh;
	
	@NotNull(message = "tenHuyen cannt be null")
    @Size(min = 1, max = 30, message = "min 1, max 50")
	private String tenHuyen;
	
	@NotNull(message = "maHuyen cannt be null")
   @Size(min = 1, max = 30, message = "min 1, max 50")
	private String maHuyen;
	
	private Set<Xa> xas = new HashSet<Xa>(0);

	public Huyen() {
	}

	public Huyen(Tinh tinh, String tenHuyen, String maHuyen) {
		this.tinh = tinh;
		this.tenHuyen = tenHuyen;
		this.maHuyen = maHuyen;
	}

	public Huyen(Tinh tinh, String tenHuyen, String maHuyen, Set<Xa> xas) {
		this.tinh = tinh;
		this.tenHuyen = tenHuyen;
		this.maHuyen = maHuyen;
		this.xas = xas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idHuyen", unique = true, nullable = false)
	public Integer getIdHuyen() {
		return this.idHuyen;
	}

	public void setIdHuyen(Integer idHuyen) {
		this.idHuyen = idHuyen;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "idTinh", nullable = false)
	public Tinh getTinh() {
		return this.tinh;
	}

	public void setTinh(Tinh tinh) {
		this.tinh = tinh;
	}

	@Column(name = "tenHuyen", nullable = false, length = 50)
	public String getTenHuyen() {
		return this.tenHuyen;
	}

	public void setTenHuyen(String tenHuyen) {
		this.tenHuyen = tenHuyen;
	}

	@Column(name = "maHuyen", nullable = false, length = 20)
	public String getMaHuyen() {
		return this.maHuyen;
	}

	public void setMaHuyen(String maHuyen) {
		this.maHuyen = maHuyen;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "huyen")
	@JsonIgnore
	public Set<Xa> getXas() {
		return this.xas;
	}

	public void setXas(Set<Xa> xas) {
		this.xas = xas;
	}

}
