package com.savis.springboot.dao.model;
// Generated Oct 2, 2017 5:48:40 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.Max;
import javax.validation.constraints.NotNull;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Tinh generated by hbm2java
 */
@Entity
@Table(name = "tinh", catalog = "mycontact")
public class Tinh implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private int idTinh;
	
	private String tenTinh;
	
	private String maTinh;
	
	private Set<Huyen> huyens = new HashSet<Huyen>(0);

	public Tinh() {
	}

	public Tinh(String tenTinh, String maTinh) {
		this.tenTinh = tenTinh;
		this.maTinh = maTinh;
	}

	public Tinh(String tenTinh, String maTinh, Set<Huyen> huyens) {
		this.tenTinh = tenTinh;
		this.maTinh = maTinh;
		this.huyens = huyens;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)

	@Column(name = "idTinh", unique = true, nullable = false)
	public int getIdTinh() {
		return this.idTinh;
	}

	public void setIdTinh(int idTinh) {
		this.idTinh = idTinh;
	}

	@Column(name = "tenTinh", nullable = false, length = 50)
	public String getTenTinh() {
		return this.tenTinh;
	}

	public void setTenTinh(String tenTinh) {
		this.tenTinh = tenTinh;
	}

	@Column(name = "maTinh", nullable = false, length = 20)
	public String getMaTinh() {
		return this.maTinh;
	}

	public void setMaTinh(String maTinh) {
		this.maTinh = maTinh;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "tinh")
	@JsonIgnore
	public Set<Huyen> getHuyens() {
		return this.huyens;
	}

	public void setHuyens(Set<Huyen> huyens) {
		this.huyens = huyens;
	}

}
