package com.savis.springboot.dao.model;
// Generated Oct 2, 2017 5:48:40 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.validation.constraints.Max;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotNull;

import org.hibernate.validator.constraints.NotBlank;

/**
 * Xa generated by hbm2java
 */
@Entity
@Table(name = "xa", catalog = "mycontact")
public class Xa implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private Integer idXa;
	
	private Huyen huyen;
	
	private String tenXa;
	
	private String maXa;

	public Xa() {
	}

	public Xa(Huyen huyen, String tenXa, String maXa) {
		this.huyen = huyen;
		this.tenXa = tenXa;
		this.maXa = maXa;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idXa", unique = true, nullable = false)
	public Integer getIdXa() {
		return this.idXa;
	}

	public void setIdXa(Integer idXa) {
		this.idXa = idXa;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "idHuyen", nullable = false)
	public Huyen getHuyen() {
		return this.huyen;
	}

	public void setHuyen(Huyen huyen) {
		this.huyen = huyen;
	}

	@Column(name = "tenXa", nullable = false, length = 50)
	public String getTenXa() {
		return this.tenXa;
	}

	public void setTenXa(String tenXa) {
		this.tenXa = tenXa;
	}

	@Column(name = "maXa", nullable = false, length = 20)
	public String getMaXa() {
		return this.maXa;
	}

	public void setMaXa(String maXa) {
		this.maXa = maXa;
	}

}
